BellumGens/bellum-gens

src/app/player-section/player-details/player-details.component.css, src/app/player-section/player-details/player-details.component.html, src/styles.scss
=> feat(player): Show progress while still loading the player profile. #10

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.component.ts, src/app/app.module.ts, src/app/home/home.component.html, src/app/login/login.component.html, src/app/notifications/notifications.component.css, src/app/notifications/notifications.component.html, src/app/notifications/notifications.component.ts, src/app/pipes/unread-notifications.pipe.ts, src/app/player-section/notifications/notifications.component.css, src/app/player-section/notifications/notifications.component.html, src/app/player-section/notifications/notifications.component.spec.ts, src/app/player-section/notifications/notifications.component.ts, src/app/team-section/team-nav/team-nav.component.css, src/app/team-section/team-notifications/team-notifications.component.html, src/app/team-section/team-notifications/team-notifications.component.ts, src/app/team-section/team-overview/team-overview.component.html, src/styles.scss
Closes #14  
Still have to include notifications for newly incoming notifications, but that's a TODO.
=> Notifications

src/app/app.module.ts, src/app/models/playerrole.ts, src/app/pipes/days-available.pipe.spec.ts, src/app/pipes/days-available.pipe.ts, src/app/pipes/open-positions.pipe.spec.ts, src/app/pipes/open-positions.pipe.ts, src/app/player-section/player-details/player-details.component.css, src/app/search/search-results/player-results/player-results.component.html, src/app/search/search-results/team-results/team-results.component.html, src/app/team-section/team-details/team-details.component.html, src/app/team-section/team-details/team-details.component.ts, src/styles.scss
Closes #1 
Still don't have regional information in the database, so for now will close with only two of the requirements met.
=> feat(search): Implementing the team summary card #1

src/app/player-section/player-details/player-details.component.css, src/app/player-section/players/players.component.css, src/app/search/search-results/player-results/player-results.component.html, src/app/search/search-results/team-results/team-results.component.html, src/app/team-section/team-details/team-details.component.css, src/styles.scss
=> feat(search): Implementing player summary cards #17

src/app/app-shell/app-shell.component.css, src/app/app-shell/app-shell.component.html, src/app/home/home.component.css, src/app/home/home.component.html, src/app/player-section/players/players.component.css, src/app/player-section/players/players.component.html, src/app/search/quick-search/quick-search.component.css, src/app/search/quick-search/quick-search.component.html, src/app/team-section/team-details/team-details.component.html, src/app/team-section/team-nav/team-nav.component.html, src/app/team-section/teams/teams.component.html, src/styles.scss
=> feat(home): Moving the home page back to single stream.

src/app/app-shell/app-shell.component.css, src/app/app.component.css, src/app/home/home.component.css
=> chore(home): Improving the home layout a little, especially on 1600px

src/app/app.component.html, src/app/login/login.component.css, src/app/login/login.component.html, src/app/player-section/notifications/notifications.component.html, src/app/player-section/player-details/player-details.component.html, src/app/search/player-search/player-search.component.html, src/app/search/quick-search/quick-search.component.html, src/app/search/team-search/team-search.component.html, src/app/team-section/team-application/team-application.component.html, src/app/team-section/team-nav/team-nav.component.html, src/app/team-section/team-notifications/team-notifications.component.html, src/app/team-section/team-strategies/team-strategies.component.html
=> chore(*): Adding ripple to all buttons

src/app/pipes/mapname.pipe.ts, src/app/team-section/team-details/team-details.component.html, src/app/team-section/team-details/team-details.component.ts, src/app/team-section/team-overview/team-overview.component.html, src/app/team-section/team-overview/team-overview.component.ts, src/app/team-section/team-strategies/team-strategies.component.html, src/app/team-section/team-strategies/team-strategies.component.ts
=> feat(team): adding checks for team members being strategy editors

src/app/home/home.component.css, src/app/home/home.component.html, src/app/home/home.component.ts, src/app/models/csgoplayer.ts, src/app/player-section/player-details/player-details.component.css, src/app/player-section/player-details/player-details.component.html, src/index.html, src/styles.scss
Closes #26
Users can search by full profile URL, custom URL username or steamId64.
=> feat(player): Adjusting the stats view for non-registered players #26 

src/app/search/search-results/player-results/player-results.component.html, src/app/search/search-results/player-results/player-results.component.ts, src/app/services/login.service.ts, src/app/success-error/success-error.component.css, src/app/success-error/success-error.component.html, src/app/team-section/teams/teams.component.html, src/styles.scss
The player search results hadn't been adjusted to not returning the roles list from the server anymore.
=> feat(notifications): Client-state updates

src/assets/weapon-icons/svg_normal/weapon_flashbang.svg, src/assets/weapon-icons/svg_normal/weapon_smokegrenade.svg, src/index.html
=> feat(twitter): Implementing a card

src/app/team-section/team-strategies/team-strategies.component.css, src/app/team-section/team-strategies/team-strategies.component.html, src/app/team-section/team-strategies/team-strategies.component.ts, src/index.html
=> Twitch strats

src/app/home/home.component.css, src/app/home/home.component.html, src/app/map-pool/map-pool.component.css, src/app/map-pool/map-pool.component.html, src/app/player-section/player-details/player-details.component.css, src/app/player-section/player-details/player-details.component.html
=> Player detail layout

package-lock.json, package.json, src/app/app.component.ts, src/app/map-pool/map-pool.component.css, src/app/player-section/player-details/player-details.component.css, src/app/team-section/team-details/team-details.component.html, src/app/team-section/team-strategies/team-strategies.component.css, src/app/team-section/team-strategies/team-strategies.component.html, src/app/team-section/team-strategies/team-strategies.component.ts, src/styles.scss
Moving player profile and stats to grid layout.
=> feat(strats): New grid layout for strats

package-lock.json, package.json, src/app/models/csgoteam.ts, src/app/player-section/notifications/notifications.component.html, src/app/player-section/notifications/notifications.component.ts, src/app/player-section/player-details/player-details.component.html, src/app/search/quick-search/quick-search.component.html, src/app/search/search-results/player-results/player-results.component.html, src/app/search/search-results/team-results/team-results.component.html, src/app/services/bellumgens-api.service.ts, src/app/team-section/team-details/team-details.component.html, src/app/team-section/team-nav/team-nav.component.html, src/app/team-section/team-nav/team-nav.component.ts, src/app/team-section/team-preferences/team-preferences.component.ts, src/app/team-section/team-strategies/team-strategies.component.css, src/app/team-section/team-strategies/team-strategies.component.ts, src/app/team-section/teams/teams.component.html, src/index.html, src/styles.scss
Urls are now with team custom urls instead of id guids.
=> feat(team): Implementing customUrl for teams

src/app/team-section/team-strategies/strategy-editor/strategy-editor.component.html, src/app/team-section/team-strategies/strategy-editor/strategy-editor.component.spec.ts, src/app/team-section/team-strategies/strategy-editor/strategy-editor.component.ts, src/styles.scss
=> fix(editor): Error after save with selected brush

src/app/player-section/notifications/notifications.component.html, src/app/player-section/notifications/notifications.component.ts, src/app/team-section/team-notifications/team-notifications.component.html, src/app/team-section/team-notifications/team-notifications.component.ts, src/app/team-section/team-strategies/strategy-editor/strategy-editor.component.html, src/app/team-section/team-strategies/strategy-editor/strategy-editor.component.ts
=> fix(*): Refactoring buttons for action in progress

azure-pipelines.yml, package-lock.json, package.json, server.ts
=> Testing SSR deployment on azure again

package-lock.json, package.json, src/app/app.server.module.ts, web.config
=> chore(*): Trying with a root web.config

package.json, server.ts
=> chore(*): Getting mad already

azure-pipelines.yml
=> chore(*):  ng universal thing is crap. I give up.

azure-pipelines.yml, browserslist, package-lock.json, package.json, predeploy.sh, server.ts, webpack.server.config.js
=> Experimenting with SSR more

package-lock.json, package.json, prerender.ts, server.ts, src/app/app-routing.module.ts, src/app/app.server.module.ts, webpack.server.config.js
=> feat(*): Adding some pre-render presets

.travis.yml, azure-pipelines.yml, src/app/app.module.ts, src/app/app.server.module.ts, src/app/player-section/player-details/player-details.component.css, src/app/player-section/player-details/player-details.component.html, src/app/player-section/player-details/player-details.component.spec.ts, src/app/search/search-results/player-results/player-results.component.html, src/app/search/search-results/player-results/player-results.component.spec.ts, src/app/search/search-results/team-results/team-results.component.html, src/app/search/search-results/team-results/team-results.component.spec.ts, src/styles.scss
=> Build definitions

azure-pipelines.yml
=> feat(prerender): Running a prerender deploy

src/app/app.component.css, src/app/app.component.html, src/app/app.module.ts, src/app/home/home.component.css, src/app/home/home.component.html, src/app/login/login-dialog/login-dialog.component.css, src/app/login/login-dialog/login-dialog.component.html, src/styles.scss
=> Fixing some issues with the landing page

src/app/search/quick-search/quick-search.component.html
=> fix(*): Fixing exception in quick search

src/app/app.component.css, src/app/home/home.component.html, src/app/services/login.service.ts, src/app/tournaments/tournament-home/tournament-home.component.html, src/app/tournaments/tournament-home/tournament-home.component.ts
=> Adding sw sub request on landing

src/app/app.component.html, src/app/app.component.ts, src/app/home/home.component.css, src/app/home/home.component.html, src/app/home/home.component.ts, src/app/services/communication.service.ts, src/app/services/login.service.ts, src/app/success-error/success-error.component.css, src/styles.scss
=> feat(*): Adding cookies message

src/app/login/login.component.html, src/app/login/login.component.ts, src/app/player-section/user-preferences/user-preferences.component.html, src/app/player-section/user-preferences/user-preferences.component.spec.ts, src/app/player-section/user-preferences/user-preferences.component.ts, src/app/services/bellumgens-api.tournaments.service.ts, src/app/tournaments/tournament-home/tournament-home.component.ts
=> feat(*): Updating user preferences

src/app/tournaments/tournament-home/tournament-home.component.html
=> fix(*): Disabling league select for non auth users

src/app/login/login.component.html, src/app/login/login.component.ts, src/app/player-section/user-preferences/user-preferences.component.ts, src/app/services/login.service.ts, src/app/tournaments/tournament-home/tournament-home.component.html, src/app/tournaments/tournament-home/tournament-home.component.ts
=> feat(*): Adding indicator that user is loading

src/app/models/tournament.ts, src/app/player-section/user-preferences/user-preferences.component.html, src/app/player-section/user-preferences/user-preferences.component.ts, src/app/services/bellumgens-api.tournaments.service.ts
=> feat(*): Exposing deletion of registrations

src/app/team-section/team-strategies/new-strategy/new-strategy.component.ts, src/app/team-section/team-strategies/strategy-editor/strategy-editor.component.ts, src/app/team-section/team-strategies/team-strategies.component.html, src/app/team-section/team-strategies/team-strategies.component.ts
=> fix(*): Team editors couldn't edit strategies

src/app/pipes/open-positions.pipe.ts, src/app/player-section/player-details/player-details.component.html, src/app/services/bellumgens-api.service.ts, src/app/team-section/team-new/team-new.component.html, src/app/team-section/team-new/team-new.component.ts
=> fix(*): Minor fixes and improvements

src/app/player-section/player-details/player-details.component.html, src/app/player-section/player-details/player-details.component.ts, src/app/services/bellumgens-api.service.ts
=> feat(*): Showing loading when switching players

src-ebleague/app/home/tournament-home.component.html
Adding information about us and a placeholder section for our partners.
=> feat(*): Adding about us info

src-bellumgens/app/team-section/team-strategies/strategy-details/strategy-details.component.ts, src-ebleague/app/app.component.html
=> fix(*): Applying minor enhancements

src-ebleague/app/tournaments/tournament-sc2/tournament-sc2.component.html
=> fix(*): Player link

src-bellumgens/app/app.component.ts, src-bellumgens/app/player-section/user-strategies/user-strategies.component.ts, src-bellumgens/app/search/search-results/player-results/player-results.component.html, src-bellumgens/app/team-section/team-strategies/strategy-details/strategy-details.component.ts, src-common/guards/adminauth.guard.spec.ts, src-common/guards/adminauth.guard.ts, src-common/models/applicationuser.ts, src-common/services/login.service.ts, src-ebleague/app/admin/admin.component.html, src-ebleague/app/admin/admin.component.spec.ts, src-ebleague/app/admin/admin.component.ts, src-ebleague/app/app-routing.module.ts, src-ebleague/app/app.module.ts, src-ebleague/app/home/tournament-home.component.html, src-ebleague/app/home/tournament-home.component.scss, src-ebleague/app/home/tournament-home.component.spec.ts, src-ebleague/app/home/tournament-home.component.ts, src-ebleague/app/tournaments/tournament-registration/tournament-registration.component.html, src-ebleague/app/tournaments/tournament-registration/tournament-registration.component.scss, src-ebleague/app/tournaments/tournament-registration/tournament-registration.component.spec.ts, src-ebleague/app/tournaments/tournament-registration/tournament-registration.component.ts, src-ebleague/app/tournaments/tournament-sc2/tournament-sc2.component.scss, src-ebleague/styles.scss
=> Participants

src-ebleague/app/tournaments/tournament-csgo/tournament-csgo.component.html, src-ebleague/app/tournaments/tournament-sc2/tournament-sc2.component.html, src-ebleague/styles.scss
=> feat(*): removing the paddings on the groups

src-common/services/login.service.ts, src-ebleague/app/admin/admin-csgo/admin-csgo.component.html, src-ebleague/app/admin/admin-sc2/admin-sc2.component.html, src-ebleague/app/tournaments/tournament-csgo/tournament-csgo.component.html, src-ebleague/app/tournaments/tournament-sc2/tournament-sc2.component.html, src-ebleague/styles.scss
=> fix(*): sizes of players and teams down to medium

src-common/models/applicationuser.ts, src-common/services/login.service.ts, src-ebleague/app/admin/admin.component.html, src-ebleague/app/admin/admin.component.ts
=> feat(*): this should return the profiles faster *performance*

src-ebleague/app/pipes/sort-by-points.pipe.spec.ts, src-ebleague/app/pipes/sort-by-points.pipe.ts, src-ebleague/app/tournaments/tournament-csgo/tournament-csgo.component.html, src-ebleague/app/tournaments/tournament-csgo/tournament-csgo.component.spec.ts, src-ebleague/app/tournaments/tournament-sc2/tournament-sc2.component.html, src-ebleague/app/tournaments/tournament-sc2/tournament-sc2.component.spec.ts, src-ebleague/app/tournaments/tournament.module.ts
=> chore(*): sorting groups by points

src-ebleague/app/admin/admin-sc2/admin-sc2.component.html
=> fix(*): wording

src-ebleague/app/tournaments/tournament-csgo/tournament-csgo.component.html, src-ebleague/app/tournaments/tournament-csgo/tournament-csgo.component.ts, src-ebleague/app/tournaments/tournament-sc2/tournament-sc2.component.html, src-ebleague/app/tournaments/tournament-sc2/tournament-sc2.component.ts
=> Twitter card update

src-common/services/bellumgens-api.tournaments.service.ts, src-ebleague/app/admin/admin-csgo/admin-csgo.component.ts, src-ebleague/app/admin/admin-sc2/admin-sc2.component.ts, src-ebleague/app/tournaments/tournament-registration/tournament-registration.component.html, src-ebleague/app/tournaments/tournament-registration/tournament-registration.component.scss, src-ebleague/app/tournaments/tournament-schedule/csgo/tournament-schedule.component.html, src-ebleague/app/tournaments/tournament-schedule/csgo/tournament-schedule.component.spec.ts, src-ebleague/app/tournaments/tournament-schedule/csgo/tournament-schedule.component.ts, src-ebleague/app/tournaments/tournament-schedule/sc2/tournament-schedule.component.html, src-ebleague/app/tournaments/tournament-schedule/sc2/tournament-schedule.component.spec.ts, src-ebleague/app/tournaments/tournament-schedule/sc2/tournament-schedule.component.ts, src-ebleague/styles.scss
=> Matches enhancements

src-bellumgens/app/app.module.ts, src-bellumgens/app/team-section/team-overview/team-overview.component.html, src-bellumgens/app/team-section/team-strategies/team-strategies.component.ts, src-bellumgens/app/team-section/team-tournaments/team-tournaments.component.html, src-bellumgens/app/team-section/team-tournaments/team-tournaments.component.scss, src-bellumgens/app/team-section/team-tournaments/team-tournaments.component.spec.ts, src-bellumgens/app/team-section/team-tournaments/team-tournaments.component.ts, src-bellumgens/styles.scss, src-common/models/tournament-schedule.ts, src-common/models/tournament.ts, src-common/services/bellumgens-api.service.ts, src-ebleague/app/tournaments/tournament-csgo/tournament-csgo.component.html, src-ebleague/app/tournaments/tournament-csgo/tournament-csgo.component.scss, src-ebleague/app/tournaments/tournament-sc2/tournament-sc2.component.html
=> Displaying matches in cs:go team profile page

src-bellumgens/app/team-section/team-tournaments/team-tournaments.component.html, src-bellumgens/app/team-section/team-tournaments/team-tournaments.component.scss
=> chore(*): restricting team name size in grid

src-ebleague/app/app.component.html
=> feat(*): adding menu entry

src-bellumgens/app/home/home.component.html, src-common/models/jerseyorder.ts, src-common/services/bellumgens-api.service.ts, src-common/services/bellumgens-api.shop.service.ts, src-common/styles.scss, src-ebleague/app/shop/shop.component.html, src-ebleague/app/shop/shop.component.scss, src-ebleague/app/shop/shop.component.ts
=> Refactoring

src-common/models/jerseyorder.ts, src-common/services/bellumgens-api.shop.service.ts, src-ebleague/app/admin/admin.component.html, src-ebleague/app/admin/admin.component.scss, src-ebleague/app/admin/admin.component.spec.ts, src-ebleague/app/admin/admin.component.ts, src-ebleague/app/admin/admin.module.ts, src-ebleague/styles.scss
=> feat(*): adding admin interface for orders

.github/workflows/nodejs.yml, src-common/models/jerseyorder.ts, src-ebleague/app/pipes/filter-sizes.pipe.ts, src-ebleague/app/raffle/raffle.component.css, src-ebleague/app/raffle/raffle.component.html, src-ebleague/app/shop/shop.component.html, src-ebleague/app/shop/shop.component.ts
=> Fix for 188

src-ebleague/app/tournaments/tournament-format/tournament-format.component.html
=> fix(*): minor bug fixes

src-ebleague/app/shop/shop.component.html, src-ebleague/app/shop/shop.component.ts
=> feat(*): jersey discounting for season 2

src-common/services/bellumgens-api.tournaments.service.ts, src-ebleague/app/admin/admin.component.html, src-ebleague/app/admin/admin.component.ts
=> feat(*): admin view of applications

src-bellumgens/app/team-section/team-tournaments/team-tournaments.component.html, src-bellumgens/app/team-section/team-tournaments/team-tournaments.component.scss, src-common/services/bellumgens-api.tournaments.service.ts, src-common/styles.scss, src-ebleague/app/admin/admin.component.html, src-ebleague/app/admin/admin.component.ts, src-ebleague/app/tournaments/tournament-csgo/tournament-csgo.component.html, src-ebleague/app/tournaments/tournament-sc2/tournament-sc2.component.html, src-ebleague/app/tournaments/tournament-schedule/csgo/tournament-schedule.component.html, src-ebleague/app/tournaments/tournament-schedule/csgo/tournament-schedule.component.ts, src-ebleague/app/tournaments/tournament-schedule/sc2/tournament-schedule.component.html, src-ebleague/styles.scss
=> feat(*): new schedule view

src-ebleague/app/home/home.component.html, src-ebleague/app/tournaments/tournament-csgo/tournament-csgo.component.html, src-ebleague/app/tournaments/tournament-csgo/tournament-csgo.component.ts, src-ebleague/app/tournaments/tournament-sc2/tournament-sc2.component.html, src-ebleague/app/tournaments/tournament-sc2/tournament-sc2.component.ts
=> fix(*): quick fixes

src-ebleague/app/admin/admin-csgo/admin-csgo.component.html, src-ebleague/app/admin/admin-csgo/admin-csgo.component.ts, src-ebleague/app/admin/admin-sc2/admin-sc2.component.html, src-ebleague/app/admin/admin-sc2/admin-sc2.component.ts
=> feat(*): adding initial filter on admin

package-lock.json, package.json, server-bellumgens.ts, server-ebleague.ts, src-bellumgens/app/app.server.module.ts, src-ebleague/app/app.server.module.ts
=> feat(*): lets see if cookies are fine now

src-common/models/tournament.ts, src-common/services/bellumgens-api.service.ts, src-common/services/bellumgens-api.shop.service.ts, src-common/services/bellumgens-api.tournaments.service.ts, src-common/services/login.service.ts, src-ebleague/app/admin/admin-sc2/admin-sc2.component.html, src-ebleague/app/tournaments/tournament-csgo/tournament-csgo.component.html, src-ebleague/app/tournaments/tournament-sc2/tournament-sc2.component.html
=> fix(*): sc2 groups and companyid for players

package-lock.json, package.json, src-common/services/bellumgens-api.tournaments.service.ts, src-ebleague/app/admin/admin-csgo/admin-csgo.component.html, src-ebleague/app/admin/admin-sc2/admin-sc2.component.html, src-ebleague/app/tournaments/tournament.component.html, src-ebleague/app/tournaments/tournament.component.scss
=> feat(*): adding groups to matches

src-ebleague/app/home/home.component.html, src-ebleague/app/home/home.component.scss, src-ebleague/app/home/home.component.ts, src-ebleague/app/tournament-registration/tournament-registration.component.html, src-ebleague/app/tournament-registration/tournament-registration.component.scss, src-ebleague/app/tournament-registration/tournament-registration.component.ts, src-ebleague/app/tournaments/tournament-format/tournament-format.component.scss, src-ebleague/locale/messages.bg.xlf, src-ebleague/locale/messages.en.xlf, src-ebleague/styles.scss
=> feat(*): landing page updates

src-bellumgens/app/player-section/user-strategies/user-strategies.component.html, src-bellumgens/app/search/search-results/player-results/player-results.component.html, src-bellumgens/app/search/search-results/team-results/team-results.component.html, src-bellumgens/app/search/search-results/team-results/team-results.component.spec.ts, src-bellumgens/app/search/search/search.component.html, src-bellumgens/locale/messages.en.xlf, src-common/models/misc.ts, src-ebleague/app/home/home.component.scss, src-ebleague/app/tournament-registration/tournament-registration.component.scss, src-ebleague/app/tournaments/production-crew/production-crew.component.html, src-ebleague/app/tournaments/production-crew/production-crew.component.scss, src-ebleague/app/tournaments/production-crew/production-crew.component.ts, src-ebleague/app/tournaments/tournament-format/tournament-format.component.scss, src-ebleague/locale/messages.bg.xlf, src-ebleague/locale/messages.en.xlf, src-ebleague/styles.scss
=> feat(*): translating crew page and BG is i18n rdy

src-common/services/bellumgens-api.tournaments.service.ts, src-ebleague/app/admin/admin-csgo/admin-csgo.component.ts, src-ebleague/app/admin/admin-sc2/admin-sc2.component.ts, src-ebleague/app/tournaments/tournament-csgo/tournament-csgo.component.ts, src-ebleague/app/tournaments/tournament-sc2/tournament-sc2.component.ts
=> fix(*): participants were not correctly returned

.github/PULL_REQUEST_TEMPLATE.md, src-bellumgens/locale/messages.bg.xlf, src-bellumgens/locale/messages.en.xlf, src-ebleague/locale/messages.bg.xlf, src-ebleague/locale/messages.en.xlf
=> Translations

src-bellumgens/app/app.component.spec.ts, src-bellumgens/app/app.component.ts, src-bellumgens/app/home/home.component.ts, src-bellumgens/app/player-section/player.component.spec.ts, src-bellumgens/app/search/search-results/player-results/player-results.component.spec.ts, src-bellumgens/app/search/search-results/team-results/team-results.component.spec.ts, src-bellumgens/app/strategies/strategies.component.spec.ts, src-bellumgens/app/strategies/strategy-details/strategy-details.component.spec.ts, src-bellumgens/app/strategies/strategy-details/strategy-details.component.ts, src-bellumgens/app/strategies/strategy-editor/strategy-editor.component.spec.ts, src-bellumgens/app/strategies/user-strategies/user-strategies.component.spec.ts, src-bellumgens/app/team-section/team-details/team-details.component.spec.ts, src-bellumgens/app/team-section/team-nav/team-nav.component.spec.ts, src-common/lib/login/user-preferences/user-preferences.component.spec.ts, src-ebleague/app/admin/admin-csgo/admin-csgo.component.spec.ts, src-ebleague/app/admin/admin-sc2/admin-sc2.component.spec.ts, src-ebleague/app/admin/admin.component.spec.ts, src-ebleague/app/app.component.spec.ts, src-ebleague/app/home/home.component.html, src-ebleague/app/news/news.component.ts
=> fix(ssr): wrapping window calls in isBrowser

src-bellumgens/messages.xlf, src-bellumgens/styles.scss, src-common/models/tournament-schedule.ts, src-common/models/tournament.ts, src-common/services/bellumgens-api.tournaments.service.ts, src-ebleague/app/admin/admin-csgo/admin-csgo.component.html, src-ebleague/app/admin/admin-csgo/admin-csgo.component.ts, src-ebleague/app/admin/admin-sc2/admin-sc2.component.html, src-ebleague/app/admin/admin-sc2/admin-sc2.component.ts, src-ebleague/app/app-routing.module.ts, src-ebleague/app/home/home.component.html, src-ebleague/app/tournaments/tournament-csgo/tournament-csgo.component.html, src-ebleague/app/tournaments/tournament-csgo/tournament-csgo.component.ts, src-ebleague/app/tournaments/tournament-sc2/tournament-sc2.component.html, src-ebleague/app/tournaments/tournament-sc2/tournament-sc2.component.ts, src-ebleague/index.html, src-ebleague/locale/messages.bg.xlf, src-ebleague/locale/messages.en.xlf, src-ebleague/styles.scss
=> feat(*): adding tournament switcher to admin

src-bellumgens/app/home/home.component.ts, src-bellumgens/app/player-section/map-pool/map-pool.component.css, src-bellumgens/app/player-section/map-pool/map-pool.component.scss, src-bellumgens/app/player-section/map-pool/map-pool.component.ts, src-common/services/bellumgens-api.tournaments.service.ts, src-common/services/login.service.ts, src-ebleague/app/home/home.component.ts, src-ebleague/app/tournaments/tournament.component.html, src-ebleague/app/tournaments/tournament.component.scss, src-ebleague/app/tournaments/tournament.component.ts, src-ebleague/locale/messages.bg.xlf, src-ebleague/locale/messages.en.xlf
=> feat(*): minor enhancements

src-bellumgens/app/app.component.scss, src-bellumgens/app/home/home.component.scss, src-bellumgens/app/notifications/notifications.component.html, src-bellumgens/app/notifications/notifications.component.scss, src-bellumgens/app/search/quick-search/quick-search.component.css, src-bellumgens/app/search/quick-search/quick-search.component.scss, src-bellumgens/app/search/quick-search/quick-search.component.ts, src-bellumgens/app/search/search-results/player-results/player-results.component.html, src-bellumgens/app/search/search-results/team-results/team-results.component.html, src-bellumgens/app/strategies/strategies.component.scss, src-bellumgens/app/team-section/team-details/team-details.component.scss, src-bellumgens/app/team-section/team.component.scss, src-bellumgens/styles.scss, src-common/lib/loading/loading.component.scss, src-common/lib/login/login-buttons/login-buttons.component.html, src-common/lib/login/login-buttons/login-buttons.component.scss, src-common/lib/login/user-preferences/user-preferences.component.html, src-common/lib/login/user-preferences/user-preferences.component.scss, src-common/styles.scss, src-ebleague/app/tournament-registration/tournament-registration.component.scss
=> refactor(*): continuing the css refactoring

src-bellumgens/app/team-section/team-tournaments/team-tournaments.component.html, src-ebleague/app/admin/admin-csgo/admin-csgo.component.html, src-ebleague/app/admin/admin-sc2/admin-sc2.component.html, src-ebleague/app/tournaments/tournament-csgo/tournament-csgo.component.html, src-ebleague/app/tournaments/tournament-sc2/tournament-sc2.component.html
=> fix(*): rowData was not correctly referenced from grid cells

azure-pipelines.yml, package-lock.json, package.json
=> fix(ssr): missing compression dependency

src-bellumgens/index.html, src-bellumgens/robots.txt, src-ebleague/index.html, src-ebleague/robots.txt
=> fix(*): og:image and twitter image source urls

projects/common/src/lib/login/login-dialog/login-dialog.component.html, projects/common/src/lib/login/login-dialog/login-dialog.component.scss, projects/common/src/styles.scss
=> fix(*): webkit autofill hax still needed

package-lock.json, package.json
=> chore(*): updating igniteui-angular

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/app/events/events.component.scss, projects/bellumgens/src/app/home/home.component.html, projects/bellumgens/src/index.html, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf
=> feat(events): updating fonts and i18n

package-lock.json, package.json, projects/bellumgens/src/app/events/events.component.scss, projects/bellumgens/src/app/events/events.component.ts
=> chore(*): updating cypress

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/app/events/events.component.ts, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf
=> feat(events): preping for tickets

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/app/events/events.component.scss, projects/bellumgens/src/app/events/events.component.ts, projects/bellumgens/src/app/home/home.component.html, projects/bellumgens/src/index.html, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf
=> feat(event): adding embedded video

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf
=> feat(event): adding main event schedule

projects/bellumgens/src/app/events/events.component.ts, projects/bellumgens/src/assets/country-flags/svg/poland.svg
=> feat(events): flipping one more player card

angular.json, package-lock.json, package.json, projects/bellumgens/src/app/app.component.html, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf
=> feat(*): adding back hammerjs and twitch link

projects/bellumgens/src/app/home/home.component.html, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf
=> feat(home): adding twitch card

projects/bellumgens/src/app/events/events.component.ts
=> feat(event): flipping one more player card

projects/bellumgens/src/app/app.component.html, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf
=> feat(events): adding events navigation

projects/bellumgens/src/index.html
=> chore(*): adding pixel

projects/bellumgens/src/app/events/events.component.html
=> feat(events): adding start time and stream link

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf
=> feat(*): updating qualifiers info

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/app/events/events.component.ts, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf
=> feat(*): filling in all player names

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf
=> feat(*): adding qualifier highlights

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf
=> feat(event): updating schedule

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/app/home/home.component.html, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf
=> feat(partners): updating BSL links

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/app/home/home.component.html
Closes #  
The link leads to a non-existent page
=> Correct links

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/app/events/events.component.ts, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf
=> feat(event): adding replay pack

.github/workflows/nodejs.yml, angular.json, cypress.config.ts, cypress/tsconfig.json, package.json, projects/bellumgens/src/app/events/events.component.ts, projects/bellumgens/tsconfig.server.json, projects/common/src/lib/pipes/sc2-race-thumb.pipe.spec.ts, projects/common/src/public_api.ts, projects/ebleague/tsconfig.server.json, tsconfig.json
=> chore(*): updating cypress action

.github/workflows/master_bellumgens.yml, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf, projects/bellumgens/src/web.config, projects/common/src/lib/registration/registration.component.html, projects/ebleague/src/locale/messages.bg.xlf, projects/ebleague/src/locale/messages.en.xlf, projects/ebleague/src/web.config
=> chore(*): updating actions versions

projects/ebleague/src/app/admin/admin-main/admin-main.component.html
=> chore(*): showing discord in the hash column

projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.html, projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.ts, projects/ebleague/src/app/tournaments/tournament-sc2/tournament-sc2.component.html
=> chore(*): multiple admin view updates

projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.html, projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.ts, projects/common/src/models/sc2maps.ts, projects/common/src/services/bellumgens-api.tournaments.service.ts, projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.html, projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.ts, projects/ebleague/src/app/tournaments/tournament-sc2/tournament-sc2.component.html, projects/ebleague/src/app/tournaments/tournament-sc2/tournament-sc2.component.ts
=> feat(events): updating map pool and persistent cache

projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.html, projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.html, projects/ebleague/src/app/tournaments/tournament-sc2/tournament-sc2.component.html
=> feat(events): updating table

projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.html, projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.scss, projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.ts, projects/bellumgens/src/app/events/league-registration/league-registration.component.html, projects/bellumgens/src/app/events/league-registration/league-registration.component.ts, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf, projects/common/src/models/tournament.ts, projects/ebleague/src/app/admin/admin-main/admin-main.component.html, projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.html, projects/ebleague/src/locale/messages.bg.xlf, projects/ebleague/src/locale/messages.en.xlf
=> feat(*): more UI adjustments

projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.html, projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.ts, projects/ebleague/src/app/admin/admin.component.scss
=> feat(*): more admin and tournament updates

projects/bellumgens/src/app/app.component.ts, projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.html, projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.scss, projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.spec.ts, projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.ts, projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/app/events/events.component.ts, projects/bellumgens/src/app/team-section/team-new/team-new.component.spec.ts, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf, projects/common/src/models/sc2maps.ts, projects/common/src/services/bellumgens-api.tournaments.service.spec.ts, projects/common/src/services/bellumgens-api.tournaments.service.ts, projects/ebleague/src/app/admin/admin-main/admin-main.component.html, projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.html, projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.scss, projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.ts, projects/ebleague/src/app/app.component.ts, projects/ebleague/src/locale/messages.bg.xlf, projects/ebleague/src/locale/messages.en.xlf
=> chore(*): adding battlenetid to applications table

projects/bellumgens/src/app/app.component.html, projects/bellumgens/src/app/events/league-registration/league-registration.component.ts
=> fix: minor fixes

projects/common/src/services/bellumgens-api.tournaments.service.ts, projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.html, projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.ts
=> feat: adding refresh buttons to admin view

projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.html, projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.scss, projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.spec.ts, projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.ts, projects/bellumgens/src/app/events/events.component.scss, projects/bellumgens/src/app/home/home.component.scss, projects/common/src/lib/registration/registration.component.html, projects/common/src/lib/registration/registration.component.spec.ts, projects/common/src/services/bellumgens-api.tournaments.service.ts, projects/common/src/styles.scss, projects/ebleague/src/app/admin/admin-main/admin-main.component.spec.ts, projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.html, projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.spec.ts, projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.ts
=> test(admin): updating test cases

projects/bellumgens/src/app/app.component.html, projects/bellumgens/src/app/app.component.ts, projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.html, projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.scss, projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.ts, projects/bellumgens/src/app/home/home.component.html, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf, projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.html, projects/ebleague/src/app/app.component.html, projects/ebleague/src/app/home/home.component.html, projects/ebleague/src/locale/messages.en.xlf
=> feat: updating social media links

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/app/events/events.component.scss, projects/bellumgens/src/app/events/events.component.ts, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf, projects/common/src/lib/success-error/success-error.component.html, projects/common/src/models/tournament.ts, projects/common/src/services/bellumgens-api.tournaments.service.spec.ts, projects/common/src/services/bellumgens-api.tournaments.service.ts, projects/ebleague/src/app/admin/admin-csgo/admin-csgo.component.ts, projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.html, projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.ts
=> feat(tickets): adding tickets links

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf, projects/ebleague/src/locale/messages.en.xlf
=> feat: adding qualifiers dates

cypress/e2e/spec.cy.ts, projects/bellumgens/src/app/app.component.html, projects/bellumgens/src/app/app.component.ts, projects/ebleague/src/app/app.component.html, projects/ebleague/src/app/app.component.ts, projects/ebleague/src/styles.scss
=> chore: removing cookies banner

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/app/home/home.component.html, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf, projects/ebleague/src/locale/messages.bg.xlf, projects/ebleague/src/locale/messages.en.xlf
=> chore: adding a map for directions to the venue

projects/bellumgens/src/app/app.component.html, projects/bellumgens/src/app/home/home.component.html, projects/bellumgens/src/app/home/home.component.scss, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf
=> feat: updating navigation entries

projects/common/src/services/bellumgens-api.tournaments.service.ts, projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.ts
=> fix: reversing the order to groups for bge balkan

projects/common/src/models/usernotifications.ts, projects/common/src/services/login.service.ts
=> feat: adding some push notification handling for checkin

projects/bellumgens/src/app/events/events.component.html
=> chore: fixing start time for balkan

projects/bellumgens/src/app/player-section/player.component.scss, projects/bellumgens/src/app/player-section/sc-player/sc-player.component.html, projects/bellumgens/src/app/player-section/sc-player/sc-player.component.scss, projects/bellumgens/src/app/player-section/sc-player/sc-player.component.ts
=> fix(sc2 player): layout of profile

projects/bellumgens/src/app/home/home.component.html, projects/bellumgens/src/app/player-section/cs-player/cs-player.component.html, projects/bellumgens/src/app/player-section/cs-player/cs-player.component.ts, projects/bellumgens/src/app/strategies/strategies.routes.ts, projects/bellumgens/src/app/team-section/team-nav/team-nav.component.html, projects/bellumgens/src/app/team-section/team.component.ts, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf, projects/common/src/lib/login/user-preferences/user-preferences.component.html, projects/common/src/models/misc.ts, projects/common/src/services/bellumgens-api.tournaments.service.spec.ts, projects/common/src/services/bellumgens-api.tournaments.service.ts, projects/common/src/services/social-media.strategy.service.spec.ts, projects/common/src/services/social-media.strategy.service.ts, projects/ebleague/src/app/admin/admin-csgo/admin-csgo.component.html, projects/ebleague/src/app/admin/admin-main/admin-main.component.html, projects/ebleague/src/app/app.routes.ts, projects/ebleague/src/app/home/home.component.html, projects/ebleague/src/app/tournament-registration/registration-success/registration-success.component.html, projects/ebleague/src/app/tournaments/tournament-csgo/tournament-csgo.component.html, projects/ebleague/src/app/tournaments/tournament-format/tournament-format.component.html, projects/ebleague/src/app/tournaments/tournament.routes.ts, projects/ebleague/src/app/tournaments/tournaments-main/tournaments-main.component.html, projects/ebleague/src/index.html, projects/ebleague/src/locale/messages.bg.xlf, projects/ebleague/src/locale/messages.en.xlf
=> chore(*): replacing all instances of cs:go

projects/bellumgens/src/app/home/home.component.html, projects/common/src/services/social-media.service.ts
=> chore: bringing back a missing image

projects/bellumgens/src/app/home/home.component.html, projects/bellumgens/src/app/home/home.component.scss, projects/bellumgens/src/app/player-section/sc-player/sc-player.component.html, projects/bellumgens/src/app/player-section/sc-player/sc-player.component.scss, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf, projects/common/src/styles.scss
=> feat: updating content on the home page and player sc2 view

projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.html, projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.html, projects/ebleague/src/app/admin/admin-sc2/admin-sc2.component.ts
=> feat: auto-select the last group and text selection for points

projects/bellumgens/src/app/app.routes.server.ts, projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.html, projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.spec.ts, projects/bellumgens/src/app/events/bge-balkan/bge-balkan.component.ts, projects/bellumgens/src/app/events/event-info/event-info.component.html, projects/bellumgens/src/app/events/event-info/event-info.component.scss, projects/bellumgens/src/app/events/event-info/event-info.component.spec.ts, projects/bellumgens/src/app/events/event-info/event-info.component.ts, projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/app/events/events.routes.ts, projects/bellumgens/src/app/events/league-registration/league-registration.component.html, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf, projects/ebleague/src/app/tournaments/tournaments-main/tournaments-main.component.html, projects/ebleague/src/locale/messages.bg.xlf, projects/ebleague/src/locale/messages.en.xlf
=> feat(qualifiers): adding participants views

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/app/events/events.component.ts, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf
=> feat(events): adding a countdown

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/app/events/events.component.ts, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf
=> feat: updating timer for the asia qualifier

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/app/events/events.component.ts, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf
=> feat(qualifiers): updating timer to european qualifier

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/app/events/events.component.scss, projects/bellumgens/src/app/events/events.component.ts, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf
=> feat(event timer): adding scroll to button

projects/bellumgens/src/app/player-section/sc-player/sc-player.component.html, projects/bellumgens/src/app/player-section/sc-player/sc-player.component.scss, projects/bellumgens/src/app/player-section/sc-player/sc-player.component.ts
=> feat(player): displaying player race in sc2 matches

projects/bellumgens/src/app/events/event-info/event-info.component.ts, projects/bellumgens/src/app/events/events.component.html
=> feat(events): closing registration for europe qualifier

projects/bellumgens/src/app/events/event-info/event-info.component.ts, projects/bellumgens/src/app/events/events.component.html
=> feat(*): disabling registration for balkan qualifier

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/app/events/events.component.spec.ts, projects/bellumgens/src/app/events/events.component.ts, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf, projects/ebleague/src/locale/messages.en.xlf
=> feat(event): adding countdown to the main event

projects/bellumgens/src/app/events/event-info/event-info.component.ts, projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/app/events/events.component.ts, projects/bellumgens/src/app/home/home.component.html, projects/bellumgens/src/app/partners/partners.routes.ts, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf
=> feat(partners): correct name for HealthyGG

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf
=> feat(event): adding info about the afterparties

projects/bellumgens/src/app/events/events.component.html, projects/bellumgens/src/locale/messages.bg.xlf, projects/bellumgens/src/locale/messages.en.xlf, projects/ebleague/src/locale/messages.en.xlf
=> feat(event): more info on afterparties and layout update
